# autogenerated by txs
#include:titlesec
\csonti#S
\title{cntitle}{entitle}#S
\makecover#S
\cover{coveryear}{covermajor}{coverclass}{covername}{coverguider}{coverdaterange}{covermonth}#S
\makecntitle#S
\makeentitle#S
\begin{cnabstract}#S
\begin{enabstract}#S
\end{cnabstract}#S
\end{enabstract}#S